# Generated by Django 3.2.7 on 2021-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('NONE', '----------'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='NONE', max_length=35),
        ),
    ]
